
name: build_firmware

on:
  push:
    branches: [ "dev" ]

    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '**.cmake'
      - '**.CMakeLists.txt'
      - 'Kconfig'
      - '**.ld'
      - '**.s'
      - '**.yml'
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened]


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xrobot-org/docker-image:main

    steps:
    - uses: actions/checkout@v3

    - name: Init submodule
      run: git submodule init && git submodule update

    - name: Build
      run: source ~/.idf_profile && python project.py build all all
