
name: pack_repo

on:
  workflow_dispatch:


jobs:
  Pack:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xrobot-org/docker-image:main
      credentials:
          username: xrobot-org
          password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Init submodule
      run: cd ${{github.workspace}} && git submodule init && git submodule update

    - name: Pack repo
      run: cd ${{github.workspace}} && zip -r ${{github.workspace}}/repo.zip ./

    - name: Create release
      run:  echo "release_name=repo.$(date +v%Y.%m.%d.vv%H.%M)" >> $GITHUB_ENV

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.release_name }}
          release_name: Repo ${{ env.release_name }}
          draft: false
          prerelease: false

    - name: Upload repo
      uses: actions/upload-release-asset@v1
      id: upload-repo
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
